### ISSUE TITLE
Integrate Coulomb Counter to BMS

### ISSUE THREAD

**Issue by knuffel-v2** [knuffel-v2/OTP15_oVario#11]
# Describe the solution you'd like
The coulomb counter should be integrated in *bms_task()*.

# Additional context
The *bms_task()* needs an additional **IPC** command queue for that, because *i2c_task()* uses the *dIDs* of the **IPC** to decode the *i2c*-addresses. The coulomb counter has a different address than the BMS IC, but I only want to use one task for handling both ICs.

**Comment by knuffel-v2** [comment]
# Todos
- [x] Initialize the coulomb counter
- [x] Read the ADC of the coulomb counter
- [ ] Read and Save the *SOC* at power up/down
